### ISSUE TITLE
Unable to Checkout on Windows

### ISSUE THREAD

**Issue by gwestwood** [lugorguk/lugorguk.github.io#2]
Use of quotation marks in filenames on Windows is prohibited:

Resolving deltas: 100% (66/66)   
Resolving deltas: 100% (66/66), done.
error: unable to create file _posts/0000-01-01-Berkshire & Thames Valley ("Silicon Corridor").md: Invalid argument
fatal: unable to checkout working tree
warning: Clone succeeded, but checkout failed.

**Comment by JonTheNiceGuy** [comment]
This should be working now? Please test and confirm :)

**Comment by gwestwood** [comment]
That was quick. I was just going to do that when I got back and had set up git on a Linux machine. :-)
All working now. 👍
