### ISSUE TITLE
Confusion around GitHub Pages vs. self-hosted jekyll

### ISSUE THREAD

**Issue by diocles** [lugorguk/lugorguk.github.io#30]
Hello!

Looking through the repo, I was confused about whether it was actually meant to be using GitHub Pages - or in other words, the difference between these URLs:

- http://testsite.lug.org.uk/
- https://lugorguk.github.io/

The github.io version works because the repository is named appropriately, but the menu doesn't have any entries.  (This is something to do with "page.lang" not existing in the sites.pages variable - if you remove the "where" filters related to language in `_includes/site-header.html` then it works again.  You can test this locally by changing the Gemfile to import 'github-pages'.)

The advantage of Github Pages is that it's hosted for you, but the downside is (obviously) that you're tied in to GitHub, and are limited to plugins they approve.  I'd propose either:

- renaming the repository to something else so that the github pages version disappears, or
- updating the Gemfile and removing the internationalization code from the header

Cheers!

Tim

**Comment by JonTheNiceGuy** [comment]
Fair. I'll rename it now :)
