### ISSUE TITLE
Theme rendering issues

### ISSUE THREAD

**Issue by JonTheNiceGuy** [lugorguk/lugorguk.github.io#5]
When rendered in a desktop browser, the page titles on the left overlap the footer (which is on the left again). When rendered on a phone, there are no page titles, and the footer is at the bottom.

I think this means we need to change the theme, but it might be something straightforward that I've missed!

**Comment by gwestwood** [comment]
Also, on the desktop, when the page width is less than about 1040 pixels, the menu on the left disappears (Tested with Firefox 60.0.1 and Chrome 66.0.3359.181).

**Comment by JonTheNiceGuy** [comment]
Perhaps this might be a better theme? http://jekyllthemes.org/themes/jekyll-theme-simple-blog/

**Comment by gwestwood** [comment]
It does look a clean, fresh one.

**Comment by gwestwood** [comment]
Had an initial look, but it's complicated by the various display options in the CSS.  Might be better to change the theme and then if the issue is still there I'll take another look.

**Comment by gwestwood** [comment]
The "Leap Day" theme also uses a very out-of-date version of normalise.css.  Latest release at https://github.com/necolas/normalize.css/blob/master/normalize.css

**Comment by JonTheNiceGuy** [comment]
Finally had a chance to go back to this. It's not "just" the normalize.css. I've looked at the other theme I suggested and tested it locally. You don't get to "just click into" the regional content in this layout, but overall, I think it works better: https://github.com/lugorguk/lugorguk.github.io/tree/SimpleBlogTheme

I'd appreciate your views @gwestwood

**Comment by gwestwood** [comment]
This looks good to me.

**Comment by JonTheNiceGuy** [comment]
Right, this has now been merged in. For some reason the options are not visible on lugorguk.github.io but are visible on https://testsite.lug.org.uk - happy to advertise this to lugmasters to get their feedback?

**Comment by gwestwood** [comment]
Note that the URL is http://testsite.lug.org.uk (https does not work).  I think sharing it with the Lugmasters would be a good idea.  Although see

**Comment by JonTheNiceGuy** [comment]
OK, I'll close this, and send an email inviting comments... :)
